### ISSUE TITLE
CC Wiki is broken and outdated, it needs a reboot, not a refresh

### ISSUE THREAD

**Issue by mattl** [cc-archive/wiki#1]
My suggestion.

We park the current CC Wiki at oldwiki.creativecommons.org and start a brand new, fresh MediaWiki install, with CCID support and port over the good content, but also consider what content belongs on the website at the same time.

WDYT @creativecommons/staff ?

**Comment by tvol** [comment]
@mattl @creativecommons/staff Sounds good.

**Comment by cablegreen** [comment]
@mattl https://github.com/mattl @creativecommons/staff
https://github.com/orgs/creativecommons/teams/staff
- 1

Cable

On Fri, Mar 6, 2015 at 9:21 AM, Timothy Vollmer notifications@github.com
wrote:

> @mattl https://github.com/mattl @creativecommons/staff
> https://github.com/orgs/creativecommons/teams/staff Sounds good.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/wiki/issues/1#issuecomment-77597806.

## 

Cable

**Comment by ryanmerkley** [comment]
+1

**Comment by RCEurope1** [comment]
+1
pls also consider CCID access for syncronizing the new CC Wiki with the CC Commentary bluespice instance.

**Comment by mattl** [comment]
Not heard of it... What is it?

**Comment by RCEurope1** [comment]
@mattl: see my email from 7/25/14, re "Wiki access for mirroring CC commentary" ...

**Comment by claudiorrrr** [comment]
+1

**Comment by mattl** [comment]
@RCEurope1 it seems down. did it ever take off?

**Comment by RCEurope1** [comment]
it's not public, b/c implementation was halted b/c syncronization module cannot be teste b/c no CC Wiki access yet b/c CC Wiki is on the backburner (I guess)

**Comment by soohyunpae** [comment]
+1 
I wonder if it's possible to make at least some parts of the old cc wiki accessible again in the meantime? Or if it will take some time, it could be nice to post an announcement that the wiki is under maintenance.

**Comment by mattl** [comment]
I will add a note to the current wiki. I'd like to move it next week.
