### ISSUE TITLE
Taking a long time to load wiki pages generally

### ISSUE THREAD

**Issue by janetpkr** [cc-archive/wiki#10]
eg. https://wiki.creativecommons.org/Web_Integration

**Comment by mattl** [comment]
Are you logged in?

**Comment by janetpkr** [comment]
![screenshot wiki error](https://cloud.githubusercontent.com/assets/6394777/8316274/b68c09b8-19aa-11e5-90b1-cffab8bc5d0c.jpg)
I get attached screen when trying to load pages.

**Comment by mattl** [comment]
Can you try again now, see if its any better? Seems like maybe you're
having connectivity issues though.

**Comment by janetpkr** [comment]
Tried again and it says I'm logged in. Able to access pages now, but still slow. I can load other webpages faster than this though. I just don't want this to be a problem for non CC-ers, eg. if I send platforms to look at https://wiki.creativecommons.org/wiki/4.0_upgrade_guidelines and they get an error or it takes a long time, that's not so good.

**Comment by mattl** [comment]
Can you log out and see if that's any faster?

**Comment by janetpkr** [comment]
It's not. Tried on firefox and chrome (where i never logged in). Chrome gets same error.

**Comment by mattl** [comment]
Okay. I suspect you're just having some connectivity issues right now. Give it another try later, or from a different location/ISP... time to do a bar crawl with your laptop, basically.

**Comment by janetpkr** [comment]
Ok.. but if I have connectivity issues isn't it more likely for others to have them too? Can't really send people to wiki pages if they don't load for them..

**Comment by mattl** [comment]
I mean, this is likely an intermittent problem. We can't guarantee our
website is up for everyone. What does http://www.whoismyisp.org/ show for
you? There's a link to share info.

**Comment by janetpkr** [comment]
AT

On Tue, Jun 23, 2015 at 1:37 PM, Matt Lee notifications@github.com wrote:

> I mean, this is likely an intermittent problem. We can't guarantee our
> website is up for everyone. What does http://www.whoismyisp.org/ show for
> you? There's a link to share info.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/wiki/issues/10#issuecomment-114634675
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mattl** [comment]
Can you share the link from the page? There's a box in the middle of the page that'll let you share your details.

**Comment by rheaplex** [comment]
Please also copy and paste a slow loading wiki url directly from the address bar here - I know it sounds silly but I just want to check we're not rewriting it in a weird way by accident.

**Comment by janetpkr** [comment]
Ok I'll reopen the issue if there is a particular page that is really slow to load. They're all a bit slow right now, but it seems as if the above error is resolved and everything is loading for me now.
