### ISSUE TITLE
Problem accessing affiliate agreement linked to from /Affiliates page

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#11]
here is error report:
![screen shot 2015-06-24 at 5 54 12 am](https://cloud.githubusercontent.com/assets/6127036/8330362/b633ba3e-1a35-11e5-9f51-063a64ce490f.png)

**Comment by rheaplex** [comment]
The agreement was deleted by mistake. I'm very sorry about that, I have now un-deleted it and it's available for download again.

Thank you for reporting this.
