### ISSUE TITLE
Lost links on main 4.0 wiki page to subject matter pages

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#12]
https://wiki.creativecommons.org/wiki/4.0

Used to have subject matter pages containing 4.0 discussions and decisions that were linked to from this main page for ease of reference, e.g. Noncommercial, Attribution, NoDerivatives.

**Comment by rheaplex** [comment]
I've added a manual copy of this list to the page. Should it need updating in future, the list should be updated here inline.
