### ISSUE TITLE
case studies form and browse all broken

### ISSUE THREAD

**Issue by janetpkr** [cc-archive/wiki#13]
eg. https://wiki.creativecommons.org/wiki/Special:BrowseData/Casestudy?_single
and when pulling from a single case study to display on pages like https://wiki.creativecommons.org/wiki/OER_Case_Studies

**Comment by rheaplex** [comment]
BrowseData is a Semantic MediaWiki extension. Semantic MediaWiki has been removed from the wiki, which means we cannot support that functionality in precisely the same way.

We can support similar functionality by linking to category pages.

**Comment by rheaplex** [comment]
I've updated the page to remove the broken markup. Sadly we cannot automatically restore the lost images.

I've updated the case study template so the individual pages render nicely again now.

Thank you for reporting this.
