### ISSUE TITLE
ODEPO database gone

### ISSUE THREAD

**Issue by janetpkr** [cc-archive/wiki#17]
Good to keep for archival purposes. Had research and data on over 1,000 OER websites: https://wiki.creativecommons.org/wiki/ODEPO

**Comment by mattl** [comment]
Some more OER-related SMW fun.

**Comment by janetpkr** [comment]
Sorry. I mean it's not imperative but I feel like it's a waste if we let it
completely disappear down a black hole.

On Wed, Jun 24, 2015 at 12:09 PM, Matt Lee notifications@github.com wrote:

> Some more OER-related SMW fun.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/wiki/issues/17#issuecomment-114983467
> .

## 

Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mattl** [comment]
Yeah, all of the content is still around, we just have to remove all the
shoehorned in attempt at using a wiki like a database.

**Comment by rheaplex** [comment]
I think mattl's comment was instructions for me. :-)

I've changed the "browse" link to point to the category page and removed unsupported functions.

I've updated the Organization template to render nicely, that may take a few hours for everything to rebuild.
