### ISSUE TITLE
case law database gone

### ISSUE THREAD

**Issue by janetpkr** [cc-archive/wiki#18]
https://wiki.creativecommons.org/wiki/Case_Law

**Comment by mattl** [comment]
@sarahpearson any idea who was updating this "database"?

**Comment by sarahpearson** [comment]
I think various past lawyers at CC did at times, and then also probably some affiliates.

**Comment by peterspdx** [comment]
Lots of lawyers have, including Kat, me, Aurelia, and I had thought Sarah but she doesn't seem to remember so I must be mistaken.  And yes, affiliates have.  I can be in charge of it. We use it a lot, at least I do whenever I get an adoption question around "are the licenses enforceable?", and so we need to keep it.

**Comment by mattl** [comment]
Cool. All of the content is there, we'll need to add some better instructions on how to add future cases.

**Comment by rheaplex** [comment]
The cases can be found using the category, which is linked from the page a couple of times.

I've added some basic (links to) instructions for adding new cases.

**Comment by peterspdx** [comment]
Thanks, Rob!!
