### ISSUE TITLE
termination of transfer pages need to be retained - main page missing

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#20]
As we're working on those with the Arcadia funding and plan to transfer this tool and related info including the FAQ to CC USA.  

https://creativecommons.github.io/labs/termination/

And other links to wiki pages in this blog post: https://creativecommons.org/weblog/entry/7163

**Comment by rheaplex** [comment]
The wiki pages:

https://wiki.creativecommons.org/wiki/ToT_Comments

https://wiki.creativecommons.org/wiki/ToT_Hypos

are both present and complete. 

How urgent is restoring the termination pages on labs? We have a project to restore the php-based sections of the site (of which this tool/FAQ is one) but if this can't wait I'll investigate it separately.

**Comment by peterspdx** [comment]
The urgency is tied to the Arcadia funding.  Would be nice to have the main tool -- the one that's been deleted and has the step-by-step determination points -- in the next week or two.  Not a pressing rush, but would like to have it by early to mid July.  Thanks!

**Comment by mattl** [comment]
@robmyers this relates to the non-blog labs content we put it in GitHub. We need to stand it up on labs.creativecommons.org somewhere and not redirect to GitHub pages.

**Comment by rheaplex** [comment]
OK I'll take a look at it on Friday while I remember. :-)

**Comment by rheaplex** [comment]
With apologies for the delay, here's the restored folder:

http://labs.creativecommons.org/demos/termination/

I am redirecting the old link here, so it still works.

(I will investigate whether the other subdirectories of /demos/ need similar redirects, but that's out of scope for this.)
