### ISSUE TITLE
fix wiki pages after migration to reintroduce ToC

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#21]
Not seeing short cuts via table of contents on pages that are quite long and have benefited from those in the past.  E.g.: https://wiki.creativecommons.org/wiki/Legal_Tools_Translation

**Comment by mattl** [comment]
It's there, see the 'contents' drop down on the far right -- but I agree it
could be a little more obvious.

@robmyers -- WDYT?

**Comment by peterspdx** [comment]
I see it now. I think the best way to characterize my input on matters like this is, I look for stuff quickly given very limited time and other pressures, and if I don't see it right away, I expect there's a problem or something could be improved.  So consider me the typical, impatient public. I am always happy to be the litmus test on usability of our site and wiki pages.

**Comment by mattl** [comment]
Yes, I suspect it's like that to make things easier for mobile users, but I
agree. We'll fix it.

**Comment by rheaplex** [comment]
Oh wow that's a bit hidden, yes thank you for reporting that @peterspdx 

@mattl - it doesn't work in mobile either. I'll re-style it and make it nicer in both with a media query.

**Comment by rheaplex** [comment]
I've changed the css (and JavaScript) to display the Table of Contents in a more traditional manner in the text, styles as a Bootstrap "well" to fit the theme.

I've tested this in various desktop and mobile sized windows but do please let me know if there are any problems.
