### ISSUE TITLE
case law database

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#22]
https://wiki.creativecommons.org/wiki/Case_Law; this page used to show a chart, now to see cases they're listed on a separate page alphabetically.  would like it to be a bit more user friendly, as we had with the chart.

**Comment by rheaplex** [comment]
Ignoring the lack of styling, is this the previous content? -

https://web.archive.org/web/20150320133934/https://wiki.creativecommons.org/Case_Law

**Comment by peterspdx** [comment]
Yup, believe so.  I'd have to check the most recent additions but yes, this is correct.  Thanks.

**Comment by peterspdx** [comment]
Reinvigorating this, as I've been asked twice in two days to point to the location where the public can easily find digestible information about enforcement actions involving CC. Today, it was The Guardian. Can we please reinstate something that is akin to the WayBackMachine's formatting? This would at least give some structure to the data for users when first encountering the database. Thanks!

**Comment by rheaplex** [comment]
I've cleaned the Case Law templates and manually recreated the list of cases on the page -

https://wiki.creativecommons.org/wiki/Case_Law

Missing or future cases will need to be added manually, I'm afraid.

**Comment by peterspdx** [comment]
wow, that's unfortunate you had to recreate it, and that so much info seems to be gone. Appreciate the effort much robmyers!

**Comment by rheaplex** [comment]
Oh which info? On the index page (which we can find and re-add) or the
individual case pages? (Which unfortunately can no longer use the features
that E.g. linked to the country for the case)
