### ISSUE TITLE
Change Scotland's status to Inactive

### ISSUE THREAD

**Issue by jessicacoates** [cc-archive/wiki#23]
Can you change CC Scotland's status to inactive on the database and remove them from the list of jurisdictions?

They've been inactive for years, so we've terminated them.

I tried editing the page directly, but it doesn't seem to have changed their status on the list.

**Comment by mattl** [comment]
Can you point me to what you changed? There's no database, so maybe you're editing something I'm unaware of.

**Comment by jessicacoates** [comment]
Ahh - then maybe what I've done is fine. I just changed it in wysiwyg on the page - you can see it in the column on the right side. https://wiki.creativecommons.org/wiki/UK:_Scotland

It used to be that the info in that column was linked to a formal database, and changing their status would remove them from the list of affiliates here: https://wiki.creativecommons.org/wiki/Category:CC_Affiliate_Locale

This has made me realise - that list is inaccurate. It includes a number of countries that have wiki pages but which aren't yet active ie we're just talking to them, or their an informal community. You can identify them by their status - only "active" teams should be on the list of affiliates eg Malta and Tunisia shouldn't be there. Neither should unported.

We definitely need to fix the list - it's our only public record of our affiliate network.

Can you easily identify which pages have which status? Or do you need me to go through manually and identify them all?

**Comment by mattl** [comment]
@robmyers one for you.

**Comment by mattl** [comment]
Rob has done this for other pages.

**Comment by rheaplex** [comment]
Taking a look.

**Comment by rheaplex** [comment]
I've changed the "Jurisdiction" template so it additionally creates a status category tag on the Wiki page.

The lists of each status are now category pages, e.g.:

https://wiki.creativecommons.org/wiki/Category:Affiliate_Inactive

They should be available tomorrow after the maintenance jobs on the wiki run tonight. If not I'll investigate further.

**Comment by jessicacoates** [comment]
Just chasing this up. The category thing doesn't seem to have worked - at least, I can't see anything on the "Inactive" page you linked to.

Any suggestions for a solution? Still important that we come up with a list of only the "active" teams for this page. If worse comes to worse, we can probably delete anything that's not "active" in its status - but for archival purposes it would be good to keep them somewhere if we can.

**Comment by rheaplex** [comment]
Thank you for chasing up.

I've rebuilt the category tables as they weren't rebuilt automatically.

UK:Scotland is now listed on the inactive page.

Affiliates with their status set to active are listed here:

https://wiki.creativecommons.org/wiki/Category:Affiliate_Active
