### ISSUE TITLE
Disable Email Editing on User Preferences Page?

### ISSUE THREAD

**Issue by rheaplex** [cc-archive/wiki#26]
CAS uses the email field to store the CCID.

Users can edit their email at:

https://wiki.creativecommons.org/wiki/Special:Preferences

Presumably if the user changes this they can no longer log in. Should we disable this or leave it as a power user feature?

**Comment by mattl** [comment]
disable it

**Comment by rheaplex** [comment]
Roger roger.

**Comment by mattl** [comment]
![maxresdefault](https://cloud.githubusercontent.com/assets/33296/9210386/db78f400-4030-11e5-8f94-d6dd9bd4822f.jpg)

**Comment by mattl** [comment]
i think disableemail might be okay.

**Comment by rheaplex** [comment]
That stops sending email to other users. I'll find the template and edit it out.

**Comment by mattl** [comment]
Okay

**Comment by rheaplex** [comment]
Done. The magic is -

$wgHiddenPrefs[] = 'emailaddress';
