### ISSUE TITLE
help determine why footnotes aren't working on the new wiki

### ISSUE THREAD

**Issue by sarahpearson** [cc-archive/wiki#27]
We have footnotes on lots of CC wiki pages, such as https://wiki.creativecommons.org/wiki/ShareAlike_compatibility_process_and_criteria and https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3. 

When editing the latter page today, I realized the footnotes aren't appearing properly on the page anymore. Then realized that seems to be the case on all wiki pages with footnotes. Is there a different way we should be doing them from now on? We had previously used

```
<ref>footnote text</ref>
```

with a

```
<references/>
```

at the end. 

Thanks!

**Comment by rheaplex** [comment]
I think this relies on the Cite extension:

https://www.mediawiki.org/wiki/Extension:Cite

@mattl Is it OK to re-install this extension?

**Comment by mattl** [comment]
Yep.

**Comment by rheaplex** [comment]
@mattl Thanks. Reinstalling.

**Comment by rheaplex** [comment]
@sarahpearson Footnotes should now work as before.
