### ISSUE TITLE
Review New Security

### ISSUE THREAD

**Issue by rheaplex** [cc-archive/wiki#28]
Please check

```
LocalSettings.php
```

on the wiki server (search for "sysop") and

```
https://wiki.creativecommons.org/wiki/Special:ListGroupRights
```

to make sure my changes to security are reasonable.

The ridiculous list of permissions is due to the "Users" (registered users) group not wanting to play nice.

I've updated the front page to ask people who want to edit to contact us.

To approve someone we add them to the "approved" group.

**Comment by mattl** [comment]
See a ticket I made in Freshdesk about this, but basically this is good... we just need a way for @mmoreshead and RCs to be able to easily verify people.

**Comment by rheaplex** [comment]
I may be able to make it so staff and RCs can add approval to people. We won't have much of a paper trail for that but it should be OK.

**Comment by mattl** [comment]
We should probably extend CCID to know about these things.

**Comment by rheaplex** [comment]
Staff and Regional can now add and remove people on the Approved group.

This will allow @mmoreshead and the RCs to approve people to post.

**Comment by mattl** [comment]
Can you make a ticket in Freshdesk with instructions?

**Comment by rheaplex** [comment]
Added a note to 15846 .
