### ISSUE TITLE
Please insert a ToC for ease of referencing subsections on this very large wiki page

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/wiki#31]
Believe this page (https://wiki.creativecommons.org/wiki/License_Versions) was going to be moved to the main website. Whether or not, it would be good to include a ToC or other page markers so we can hyperlink to the section we want to reference. It's a very long and content-rich page that I use with some frequency. Would like to be able to point to some part or another, even if roughly. Thanks!

**Comment by mattl** [comment]
Done.

(FYI, any long wikipage will have a TOC unless, as this page did, you have `__NOTOC__` at the top of the page)
