### ISSUE TITLE
provide examples of attribution for various social media sites

### ISSUE THREAD

**Issue by tvol** [cc-archive/wiki#33]
these questions keep getting asked on social media, and we do not have any examples that related to attribution on twitter, facebook, etc. https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

**Comment by janetpkr** [comment]
Wouldn't it just be a simplified version of what's already on the wiki? If you have a suggestion for adding a section, happy to hear.

I think our efforts are better spent on automating attribution through projects like the EXIF one which would get carried across social media sites. We can provide guidance on attribution all we like, but esp in the social media realm, only a few users would follow them and it's like a drop in the bucket.
