### ISSUE TITLE
missing affiliate teams on https://wiki.creativecommons.org/wiki/Category:CC_Affiliate_Locale

### ISSUE THREAD

**Issue by tvol** [cc-archive/wiki#34]
I noticed that some of the teams reporting from the annual survey are not on the list of teams on the CC Wiki. These include Cyprus, El Salvador, and Ethiopia. @gwenfranck or @RCEurope1 can you add them?

**Comment by RCEurope1** [comment]
thx for spotting, respective RCs will take care of that ...

**Comment by tvol** [comment]
thanks

**Comment by claudiorrrr** [comment]
I'm working with the folks from El Salvador.

**Comment by mmoreshead** [comment]
I wonder what the difference is between that page and this page? https://wiki.creativecommons.org/wiki/Category:Affiliate_Active

**Comment by claudiorrrr** [comment]
> I wonder what the difference is between that page and this page? https://wiki.creativecommons.org/wiki/Category:Affiliate_Active

Side note: You have no idea how I hate that page.
