### ISSUE TITLE
can't upload pdf file to CC wiki

### ISSUE THREAD

**Issue by tvol** [cc-archive/wiki#36]
<img width="513" alt="screen shot 2016-05-24 at 12 46 06 pm" src="https://cloud.githubusercontent.com/assets/231665/15517657/d0483302-21ad-11e6-9e8c-5cc928c87b15.png">

**Comment by mattl** [comment]
@robmyers Upgrade revert the permissions?

**Comment by rheaplex** [comment]
@mattl Permissions and directory group.

@tvol This is now fixed. Thank you for reporting this problem.
