### ISSUE TITLE
CCID authorisation requests

### ISSUE THREAD

**Issue by soohyunpae** [cc-archive/wiki#37]
Hi @robmyers 

Lucien Lin (CCID-lucienchlin) and Yi Zheng (zhengyi@cn.creativecommons.org) say they have a CCID but need it authorised. I just forwarded their emails to you.
Can you please help them ASAP? Sorry, this is quite urgent...

Thanks so much!

Soohyun

**Comment by mmoreshead** [comment]
Hi @soohyunpae - I can take care of these for you anytime.  Lucien Lin's wiki account is approved!

**Comment by rheaplex** [comment]
Thank you @mmoreshead!

**Comment by soohyunpae** [comment]
Awesome! @mmoreshead Thanks so much!
