### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by soohyunpae** [cc-archive/wiki#38]
I'm trying to edit the page for 4.0 Chinese translation(https://wiki.creativecommons.org/wiki/Legal_Tools_Translation/4.0/Chinese) but still getting an error message (please see my email for details).

Can you please look into this issue asap? I know you are already super busy with the new website, but this is very important for many affiliates in our region. Thanks so much in advance!

Soohyun

**Comment by mmoreshead** [comment]
Thanks @gwenfranck but I think this is a different issue, I can't log in either!
For @mattl and @robmyers, here's the error: 

Secure Connection Failed

An error occurred during a connection to wiki.creativecommons.org:80. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by rheaplex** [comment]
@mmoreshead thank you for the deets.

@mattl looks like we need to fix ssl. Or tls, as the cool kids call it now.

**Comment by rheaplex** [comment]
@soohyunpae We have to fix the https:// connection on that box but we won't be able to do it until Monday. I'm very sorry about the delay.

**Comment by rheaplex** [comment]
I'm sorry this took so long. :-( It is now fixed! :-)

**Comment by soohyunpae** [comment]
Thanks a lot @robmyers but it seems wiki is down again :(

Here's the error msg:

Website is offline No cached version of this page is available.
Error 522 Ray ID: 2ba70aff66f30607 • 2016-06-29 05:42:14 UTC
Connection timed out

**Comment by mattl** [comment]
I think that was just bad timing... the server went down for a moment.

Please try again now.

**Comment by soohyunpae** [comment]
Oh I should've been more patient! ;) Thanks @mattl !
