### ISSUE TITLE
Cannot edit

### ISSUE THREAD

**Issue by soohyunpae** [cc-archive/wiki#39]
Hi @mmoreshead 

Wiki is now back (yay!) but I cannot edit - I had no problem editing it before.
Can you have a look please?

Here's the error in case you need it:

You do not have permission to edit this page, for the following reason:

The action you have requested is limited to users in one of the groups: Administrators, approved, staff, regional, affiliate, community.

Thanks!

**Comment by mmoreshead** [comment]
Approved, let me know if it's not working (because that would mean it's something else).
