### ISSUE TITLE
re-instate (or find suitable replacement for) Edit with form

### ISSUE THREAD

**Issue by RCEurope1** [cc-archive/wiki#4]
in the long-running instance of the CC Wiki there were 2 options to edit certain page types, "Edit" and "Edit with form". The latter proved quite valuable to guide affiliates when editing/adding pages. This made sure the result was sort of well-structured. Forms seem to be generally unsupported after the Wiki reboot, but this feature should either be re-instated or substituted by something equally powerful.

**Comment by mattl** [comment]
We probably won't fix this. We'll instead provide a better place for structured data to live.

**Comment by RCEurope1** [comment]
any news on the better place thing?
