### ISSUE TITLE
Jennie needs edit access on CC Wiki

### ISSUE THREAD

**Issue by little-wow** [cc-archive/wiki#40]
Could I gain the ability to edit the wiki?

**Comment by mmoreshead** [comment]
Can you tell me your CCID, @little-wow?

**Comment by mmoreshead** [comment]
(after you log into the wiki, you can see it up on the top right side.)

**Comment by little-wow** [comment]
CCID-jennierosehalperin

**Comment by mmoreshead** [comment]
Done and done, edit to your heart's content!
