### ISSUE TITLE
permission to delete pages on the wiki

### ISSUE THREAD

**Issue by mmoreshead** [cc-archive/wiki#42]
Hey, can I get permission to delete pages?  I found some new spam ones like this https://wiki.creativecommons.org/index.php?title=Call_Florida...(1.8.0.0.8.6.0.9.2.3.0_Quickbooks_p.r.o_s.u.p.p.o.r.t._p.h.o.n.e_n.u.m.b.e.r,_Quickbooks_t.e.c.h_s.u.p.p.o.r.t_n.u.m.b.e.r&redirect=no  

And I've already pulled permission from that user.
~Mari

**Comment by rheaplex** [comment]
Eek how are they getting through?

I'll make sure you have the relevant permissions then show you how to clean
up quickly after them. Do you have ten minutes for a call about this on
Monday?

**Comment by mmoreshead** [comment]
@robmyers Let me catch up on regular stuff today and we can talk on Tuesday!

**Comment by rheaplex** [comment]
OK cool! :-)

**Comment by rheaplex** [comment]
I've given you super-powers on the wiki. Please use them only for good.

See here for a guide to how to handle spammers -

https://github.com/creativecommons/wiki/wiki/How-to-clean-up-a-spammer

This particular spammer was confirmed after email contact. :-( We may have to tighten the criteria even further, which would be a shame.

**Comment by mmoreshead** [comment]
Thanks @robmyers - I've now started asking people what they plan on editing (not in mean way like detective might ask, more like how a cheerleader might ask a pledge why they want to join the best squad around sort of way).  I promise to use my powers for good.

**Comment by rheaplex** [comment]
That sounds great. It's a shame we can't just have a registration form containing an "Are you evil?" checkbox but I'm not sure spammers would go for it...
