### ISSUE TITLE
CCID validation emails not sending.

### ISSUE THREAD

**Issue by mmoreshead** [cc-archive/wiki#43]
As suspected in https://github.com/creativecommons/creativecommons.org/issues/402 -- and confirmed by an email from Maarten: "I’m trying to activate my CCID account, but I get no confirmation mail, also not in my spam. What to do?"

Help?

**Comment by mattl** [comment]
So I hate to say it but "it works for me" -- I'll look into it more
shortly.

**Comment by mattl** [comment]
I can see it delivered to the kl.nl server. Possible that they're blocking
sendgrid?

**Comment by mzeinstra** [comment]
I've tried to reset my password again to trigger the validation mail. I can reset my password but once I try to log in on the wiki I get: https://wiki.creativecommons.org/wiki/ValidateReminder

I received only a mail with

Update to your Creative Commons account

```
Your password has been reset on your Creative Commons ID. Thanks for supporting Creative Commons.
```

**Comment by mattl** [comment]
Seems like there's a bug here :)  how urgently do you need wiki access?

**Comment by mmoreshead** [comment]
Not urgent as I understand it.  I flagged that the tech team is out of the office today.

**Comment by mzeinstra** [comment]
Indeed not urgent.

**Comment by mmoreshead** [comment]
This is still broken, sadly :(

**Comment by mmoreshead** [comment]
Just joking, it worked.

**Comment by rheaplex** [comment]
Oh good. :-) I just tested the mail daemon on the ccid server so that's certainly working.

I agree with Matt that any problems are probably at the spam filter level.
