### ISSUE TITLE
Authorize user

### ISSUE THREAD

**Issue by claudiorrrr** [cc-archive/wiki#46]
user: mvr21
Thanks! ;)

**Comment by mmoreshead** [comment]
Hey @claudioruiz - you can always assign these to me and I'll get them done.  The wiki is down for the moment so I'll get to this when it comes back.

**Comment by mmoreshead** [comment]
@claudioruiz User doesn't exist.  You sure the CCID is right?  They must validate their CCID (just click a link in their email after they register) and I know this was maybe broken before so not sure if that's the same issue here.

**Comment by claudiorrrr** [comment]
@mmoreshead checking with the affiliates :|
