### ISSUE TITLE
Increase allowed file size for upload

### ISSUE THREAD

**Issue by mmoreshead** [cc-archive/wiki#48]
Hi, no matter what I do, I cannot get this file below 5MB so i can upload it to the wiki.  Can you increase the allowed file size, if only temporarily for me?  I can get it down to 6.4 but that's it.  Help?

**Comment by rheaplex** [comment]
Hmm we should accept larger than that given the current settings. I tweaked some settings that shouldn't affect it, see if that has convinced it to co-operate?

If not could you post the exact error message?

Thank you!

**Comment by mmoreshead** [comment]
On the file upload page, it says 
Maximum file size: 5 MB
--
Permitted file types: png, gif, jpg, jpeg, pdf.

The error I get after I try to upload says:

"This file is bigger than the server is configured to allow."

**Comment by rheaplex** [comment]
Erk. OK let me see where it's getting that from.

**Comment by rheaplex** [comment]
It's now 20MB. The 5MB was hiding somewhere. :-)
