### ISSUE TITLE
OER Policy Registry (not working)

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/wiki#5]
https://wiki.creativecommons.org/wiki/OER_Policy_Registry

The OER Policy Registry is one of our important open policy projects.  I think it used "Semantic MediaWiki functionality" - is that why it has code on the home page ... and none of the features work any longer?

Thanks for fixing ... people around the world (governments, open orgs, advocates, IOL fellows, etc.) use it to review OER open policies - and share their OER policies.

Tim and I will be working with Matt and Rob to create an OPN "Open Policy Registry" ... and then migrate the OER Policy Registry over to it.  Until that is done, we need the existing OER policy registry to work.

Many thanks - Cable

**Comment by mattl** [comment]
@cablegreen The data is all there, we just need to make it a little more 'browseable' for now until an actual database can be put in place.

**Comment by mattl** [comment]
https://wiki.creativecommons.org/wiki/Category:OER_Policy_Registry

**Comment by cablegreen** [comment]
Thanks - please ping me when it's up and running again and I'll take a look.  Gratefully,

**Comment by cablegreen** [comment]
Thanks - please ping me when it's up and running again and I'll take a look.  Gratefully,

**Comment by cablegreen** [comment]
On: https://wiki.creativecommons.org/wiki/Category:OER_Policy_Registry
Is there a way to:
- add new open policies?
- filter by any of the meta-data: national, proposed, etc?

**Comment by mattl** [comment]
There's no way to add new policies. This has been the case for some time.

There may be something we can do improve filtering. 

For now I have put up a stop-gap page at https://wiki.creativecommons.org/wiki/OER_Policy_Registry and moved the previous page to https://wiki.creativecommons.org/wiki/OER_Policy_Registry-previous

**Comment by cablegreen** [comment]
1. Jane added a few policies just a few weeks ago... so it was working.
2. At a minimum, I need CC staff to be able to add new and exit existing open policies.
3. It would also be very nice to have some filtering options - many thanks.

**Comment by mattl** [comment]
@robmyers I'm heading out as I'm way overdue to leave.

maybe we should get Lucene working on the wiki so we can do better searches.

@cablegreen OER policies will be addable, but they'll rely on a bit more wiki-knowhow for now (copying and pasting an existing one made as a template would be my suggestion) -- the form-related things won't be returning.

**Comment by rheaplex** [comment]
Yes people can edit the template markup, all the information is still there and editable/addable-to.

I'll see what we can restore to the index page now, as a matter of urgency.

**Comment by cablegreen** [comment]
Thanks gents - standing by. Any solution is fine with me - as long as it is relatively easy to:
- add new and exit existing open policies
- enable some filtering options for users

**Comment by rheaplex** [comment]
I've restored as many of the searches as possible - I couldn't restore "No Status".

The list of policies has been replaced with a link to the policy category page.

The policy creation section now explains that people should use the template directly, I've added some minimal instructions for this to the template page and told people how to get more help if they need it.

**Comment by cablegreen** [comment]
Thanks Rob!

on: https://wiki.creativecommons.org/wiki/OER_Policy_Registry

(1) In the opening sentence - "current" and "proposed" are not linked to the right pages.  Note: they do work below under "popular searches."
(2) First sentence - please link "OER" to: https://creativecommons.org/education
(3) "By Country" - possible to have a pull down menu to select any country?  

Thank you, Cable

**Comment by rheaplex** [comment]
@cablegreen I've added links for 1 and 2, and created a list of pages for 3 (we can't do a pop-down menu). I re-arranged the horizontal order of the lists lists so hopefully this looks OK. If someone adds a country that isn't on there, we will need to add it by hand

For 3 we need to regularize the ways people say United States/USA/United States of America, and to decide whether to change wales to "United Kingdom".

**Comment by cablegreen** [comment]
Thanks for 1 and 2 - looks great.

For 3:
(a) Let's go with "United States of America" - can you do a find / replace and change them all to: "United States of America" ?

(b) Let's leave Scotland and Wales separate for the OER Policy Registry... thanks.

**Comment by rheaplex** [comment]
a) name regularized to "United States of America"

b) separate entries for Scotland and Wales created.
