### ISSUE TITLE
Lost affiliates list

### ISSUE THREAD

**Issue by jessicacoates** [cc-archive/wiki#6]
With the migration we seem to have lost the list of affiliates that used to live at: https://wiki.creativecommons.org/wiki/CC_Affiliate_Network

It was automatically generated from the community database that lived on the wiki. Each country where we have contacts has a page, with a status on the side. When the status is set to active, they automatically appeared on the list. 

This was our definitive public list of affiliates, so it's important we get it restored.

Let me know if you need to know anything else.

**Comment by rheaplex** [comment]
I'll take a look at this. Thank you for reporting it.

**Comment by rheaplex** [comment]
For now I've replaced the list with a link to a search for active Jurisdictions. I'll discuss this with Matt next week.

**Comment by mattl** [comment]
This looks okay (apart from 'click here') -- but I suggest we extend the template all these pages are using and add them to a category, and then simply link to the category page.

**Comment by rheaplex** [comment]
Will do.

Can we do that for the OER policies as well, e.g. expand the Country into a category.

**Comment by rheaplex** [comment]
I've implemented that for Jurisdictions and added the link. Thank you to @mattl for helping with that.
